eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


microservices:
  payment-service:
    endpoints:
      fetchPaymentById:
        uri: http://PAYMENT-SERVICE/payments/
  user-service:
    endpoints:
      fetchPaymentById:
        uri: http://USER-SERVICE/user/

test:
  input:1
